/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * View.java
 * author 涌井
 * Created on 2011/04/18, 14:45:17
 */

package conescala;


public class StartView extends javax.swing.JFrame {
	//private Main m;

    /** Creates new form View */
    public StartView() {
    	//this.m = m;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttons = new javax.swing.ButtonGroup();
        startMeasure = new javax.swing.JButton();
        pk2 = new javax.swing.JRadioButton();
        pq5 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("cone plate");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        startMeasure.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        startMeasure.setText("(^O^)正しく測る ISO");
        startMeasure.setName("startMeasure"); // NOI18N
        startMeasure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startMeasureActionPerformed(evt);
            }
        });

        buttons.add(pk2);
        pk2.setSelected(true);
        pk2.setText("通常の絵具");
        pk2.setActionCommand("normalColor");
        pk2.setName("pk2"); // NOI18N
        pk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pk2ActionPerformed(evt);
            }
        });

        buttons.add(pq5);
        pq5.setText("クイックベース等");
        pq5.setActionCommand("quickBase");
        pq5.setName("pq5"); // NOI18N

        jButton1.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jButton1.setText("(`д')すぐ測る USO");
        jButton1.setName("flyingMeasure");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flyingMeasureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pq5)
                            .addComponent(pk2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(startMeasure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(pk2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pq5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startMeasure)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startMeasureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startMeasureActionPerformed
        Main.startMeasure(pk2.isSelected() ? 0 : 1);
    }//GEN-LAST:event_startMeasureActionPerformed

    private void pk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pk2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.out.println("exiting...");
        Main.quit();
    }//GEN-LAST:event_formWindowClosing

    private void flyingMeasureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flyingMeasureActionPerformed
      Main.flyingMeasure(pk2.isSelected() ? 0 : 1);
    }//GEN-LAST:event_flyingMeasureActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttons;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton pk2;
    private javax.swing.JRadioButton pq5;
    private javax.swing.JButton startMeasure;
    // End of variables declaration//GEN-END:variables

}
